apiVersion: v1
kind: Service
metadata:
  name: mtg-deck-shuffler-service
  labels:
    app: mtg-deck-shuffler
spec:
  selector:
    app: mtg-deck-shuffler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
  type: ClusterIP  # Internal service for ALB Ingress